/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    kotlin("jvm")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

val dropwizardVersion: String by project
val retrofitVersion: String by project
val shpGamesDropwizard2ApiVersion: String by project
val shpGamesApiClientUtils: String by project
val ktorVersion: String by project
val jacksonVersion: String by project

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:$jacksonVersion")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:$jacksonVersion")
    api("com.michael-bull.kotlin-inline-logger:kotlin-inline-logger:1.0.2")
    //implementation("shp.games.backend-commons:shp-games-query:0.4.22")

    //implementation("shp.games.backend-commons:shp-api-client-utils:$shpGamesApiClientUtils")
    //implementation("shp.games.backend-commons:shp-games-dropwizard2-api:$shpGamesDropwizard2ApiVersion")
    //implementation("shp.games.backend-commons:shp-ktor-authentication:1.0.0-SNAPSHOT")
    //implementation("io.dropwizard:dropwizard-core:$dropwizardVersion")
    implementation("com.squareup.retrofit2:retrofit:$retrofitVersion")
    implementation("com.squareup.retrofit2:converter-jackson:$retrofitVersion")

    // ktor
    implementation("io.ktor:ktor-locations:$ktorVersion")
    implementation("io.ktor:ktor-auth:$ktorVersion")
    implementation("io.ktor:ktor-auth-jwt:$ktorVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-server-host-common:$ktorVersion")
    implementation("io.ktor:ktor-metrics-micrometer:$ktorVersion")
    implementation("io.ktor:ktor-jackson:$ktorVersion")

    implementation(project(":exchange-entities"))
    //api(project(":shp-games-query-v2"))

    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}
