/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/5.1/userguide/multi_project_builds.html
 */

rootProject.name = "crypto-exchange"

includeComponent("exchange-api-core")
includeComponent("exchange-entities")
includeComponent("blockchain-client")
includeComponent("blockchain-provider")
includeComponent("eth-blockchain-client")
includeComponent("contracts")
includeComponent("codegen")
includeApp("exchange-api")

fun includeComponent(componentName: String) {
    include(componentName)
    project(":$componentName").projectDir = File(settingsDir, "./components/$componentName")
}


fun includeApp(appName: String) {
    include(appName)
    project(":$appName").projectDir = File(settingsDir, "./apps/$appName")
}

